### ISSUE TITLE
Cross-compile for Play 2.6

### ISSUE THREAD

**Issue by KarelCemus** [splink/pagelets#5]
Play 2.6 supports both Scala 2.11 and Scala 2.12. Could you cross-compile and publish pagelets? Version `0.0.4` is published only for Scala 2.12.

Thanks

**Comment by splink** [comment]
Hey Karel, 
from version 0.0.7 on pagelets is cross published for scala 2.11 and 2.12. 
Cheers, Max

**Comment by KarelCemus** [comment]
Great, thanks
