### ISSUE TITLE
Title in Template

### ISSUE THREAD

**Issue by ASchmidt84** [splink/pagelets#6]
Hi,
I started with an integration of pagelet for a project. But now I am a little bit confused.
You described in this readme the access to the title with 
```
@page.head.title
```
But this field does not exists. I gave the title in this 
```
def index = PageAction.async(routes.ErrorController.internalServerError())(implicit r => Messages("title"), tree){ (request, page) =>
    mainTemplate(request)(page)
  }
```
with Message("title").
But I have no access to title in template. And their is also no header entry. What is to do to access the title?
Thank you.

**Comment by splink** [comment]
Hi,
it looks like a Bug. For the time being, you could pass the title manually to the main template from within the Action.

Cheers,
Max
